routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/login', 'LoginController@index')->name('login.index');
Route::post('/login', 'LoginController@authenticated');
Route::get('/logout', 'LoginController@SignOut')->name('logout.index');

//middleware for check login
Route::group(['middleware' => ['login']], function () {

    //Dashboard
    Route::get('/', 'HomeController@index')->name('home.index');

    //point of sale
    Route::get('pointofsale/', 'PointOfSaleController@index')->name('pointofsale.index');
    Route::post('pointofsale/searchlive', 'PointOfSaleController@liveSearchMedicine')->name('pointofsale.liveSearch');
    Route::post('pointofsale/search/medicine', 'PointOfSaleController@medicinSearch')->name('pointofsale.searchMedicine');

    //purchase Medicine
    Route::get('purchasemedicine/', 'PurchaseController@index')->name('purchase.index');
    Route::post('purchasemedicine/searchlive', 'PurchaseController@liveSearchMedicine')->name('purchase.liveSearch');
    Route::post('purchasemedicine/search/medicine','PurchaseController@medicinSearch')->name('purchase.searchMedicine');


    //invoice routes
     //invoice routes
    Route::post('/invoice', 'InvoiceController@addtocart')->name('invoice.add');
    Route::post('/invoice/save', 'InvoiceController@saveInvoice')->name('invoice.save');
    Route::get('/invoice/{id}', 'InvoiceController@deleteInvoiceItem')->name('invoice.delete');


    //Manage Category
    Route::get('/Category/', 'CategoryController@index')->name('Category.index');
    Route::get('/Category/create', 'CategoryController@create')->name('Category.create');
    Route::post('/Category', 'CategoryController@store')->name('Category.store');
    Route::get('/Category/edit/{id}', 'CategoryController@edit')->name('Category.edit');
    Route::patch('/Category/{id}', 'CategoryController@update')->name('Category.update');
    Route::get('/Category/destroy', 'CategoryController@destroy')->name('Category.destroy');

    //Manage Medicine
    Route::get('/medicine/list', 'MedicineController@index')->name('medicine.index');
    Route::get('/medicine/create', 'MedicineController@create')->name('medicine.create');
    Route::post('/medicine/store', 'MedicineController@store')->name('medicine.store');
    Route::get('/medicine/destroy', 'MedicineController@destroy')->name('medicine.destroy');
    Route::get('/medicine/edit/{id}', 'MedicineController@edit')->name('medicine.edit');
    Route::post('/medicine/{id}', 'MedicineController@update')->name('medicine.update');
    Route::get('/medicine/shortage', 'MedicineController@shortage')->name('medicine.shortage');
    Route::get('/medicine/details/{id}', 'MedicineController@details')->name('medicine.details');
    Route::get('/medicine/expired', 'MedicineController@expired')->name('medicine.expired');
    Route::get('/medicine/nearexpired', 'MedicineController@nearExpired')->name('medicine.nearexpired');

    //Manage Executives
    Route::resource('executive', 'ExecutiveController');
    Route::post('/executive/{id}', 'ExecutiveController@update')->name('executive.update');

    //Settings
    Route::get('/setting/activitylog', 'SettingController@activityLog')->name('setting.activity');
    Route::get('/setting/remainder', 'SettingController@remainderSetting')->name('setting.remainder');
    Route::post('/setting/remainder', 'SettingController@remainderChange')->name('setting.update');

    Route::get('/medicine/search', 'MedicineController@searchByGenericOrClassName')->name('medicine.search');

    //Manage Expenses catagory
    Route::get('/expense-category', 'ExpensecategoryController@index')->name('expense-category.index');
    Route::get('/expense-category/create', 'ExpensecategoryController@create')->name('expense-category.create');
    Route::post('/expense-category', 'ExpensecategoryController@store')->name('expense-category.store');
    Route::get('/expense-category/{id}', 'ExpensecategoryController@edit')->name('expense-category.edit');
    Route::patch('/expense-category/{id}', 'ExpensecategoryController@update')->name('expense-category.update');
    Route::get('/destory-expense-category', 'ExpensecategoryController@destroy')->name('expense-category.destroy');

    //expense related route
    Route::resource('expense', 'ExpenseController');

    //Manage Supplier
    Route::resource('supplier', 'SupplierController');
    Route::post('/supplier/{id}', 'SupplierController@update')->name('supplier.update');
    Route::get('/delete-supplier', 'SupplierController@delete')->name('supplier.delete');
    Route::get('/supplier/details', 'SupplierController@details')->name('supplier.details');



    //report related routes
     Route::get('/report/salesitems', 'SalesItemsController@index')->name('salesitem.index');
     Route::get('/report/date-wise-invoices-index', 'SalesItemsController@dateWiseInvoiceIndex')->name('datewise.index');
     Route::post('/report/date-wise-invoices-list', 'InvoiceController@dateWiseInvoiceReport')->name('datewise.Invoices');
     Route::get('/report/invoice-details/{invoice_number}', 'SalesItemsController@invoiceDetails')->name('invoice.details');
});

resources/views/pages/manage_executive/create.blade.php
@extends('layouts.master')
@section('css')
    <style>
        hr {
            display: block;
            margin-top: 0.5em;
            margin-bottom: 0.5em;
            margin-left: auto;
            margin-right: auto;
            border-style: inset;
            border-width: 1px;
        }
    </style>

    <script>
        function showMyImage(fileInput) {
            var files = fileInput.files;
            for (var i = 0; i < files.length; i++) {
                var file = files[i];
                var imageType = /image.*/;
                if (!file.type.match(imageType)) {
                    continue;
                }
                var img = document.getElementById("thumbnil");
                img.file = file;
                var reader = new FileReader();
                reader.onload = (function (aImg) {
                    return function (e) {
                        aImg.src = e.target.result;
                    };
                })(img);
                reader.readAsDataURL(file);
            }
        }
    </script>

@endsection

@section('content')
    <br>
    <div class="br-pagebody">
        <div class="br-section-wrapper">

            @include('include._message')

            <div class="row">
                <div class="col-lg-3">
                    <h5>Add New Executive</h5>
                </div>
            </div>
            <hr>
            <br>

            <div class="form-layout form-layout-1">
                <form method="POST" action="{{route('executive.store')}}" enctype="multipart/form-data">
                    @csrf

                    <div class="row">
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="form-control-label">Executive Name<span class="tx-danger">*</span></label>
                                <input class="form-control" type="text" name="user_name" value="{{old('user_name')}}"
                                       placeholder="executive name">
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="form-control-label">Executive Email<span
                                        class="tx-danger">*</span></label>
                                <input class="form-control" type="text" name="email" value="{{old('email')}}"
                                       placeholder="executive email">
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="form-control-label">Executive Phone<span
                                        class="tx-danger">*</span></label>
                                <input class="form-control" type="text" name="user_phone" value="{{old('user_phone')}}"
                                       placeholder="executive phone">
                            </div>
                        </div>

                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="form-control-label">Joining Date:<span class="tx-danger">*</span></label>
                            <input type="text" id="datepicker" value="{{old('joining_date')}}" width="400" name="joining_date" class="form-control" placeholder="yy/mm/dd">
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="form-control-label">Password<span class="tx-danger">*</span></label>
                                <input class="form-control" type="password" name="password" value="{{old('password')}}"
                                       placeholder="password">
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="form-control-label">Address<span class="tx-danger">*</span></label>
                                <input class="form-control" type="text" name="user_address"
                                       value="{{old('user_address')}}" placeholder="address">
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-lg-6">
                            <img style="width:20%; margin-top:10px;" id="thumbnil" name="thumbnil" src="" alt="image"/>
                            <br>
                            <input type="file" for="thumbnil" name="image" accept="image/*" onchange="showMyImage(this)"/>
                        </div>

                    </div>
                    <br>

                    <div class="form-layout-footer">
                        <button class="btn btn-info">Save Information</button>
                    </div><!-- form-layout-footer -->
            </div><!-- form-layout -->

@endsection

@section('js')
<script>
        $("#datepicker").datepicker({ dateFormat: "yy-mm-dd" });
</script>
@endsection

resources/views/pages/manage_executive/details.blade.php
@extends('layouts.master')
@section('css')
    <style>
        hr {
            display: block;
            margin-top: 0.5em;
            margin-bottom: 0.5em;
            margin-left: auto;
            margin-right: auto;
            border-style: inset;
            border-width: 1px;
        }
    </style>

@endsection

@section('content')
    <br>
    <div class="br-pagebody">
        <div class="br-section-wrapper">


            <div class="row">
                <div class="col-lg-3">
                    <h5>Executive Details</h5>
                </div>
            </div>
            <hr>
            <br>

            <div class="form-layout form-layout-1">
                <div class="row">
                    <div class="col-lg-6">
                        <img src="{{URL::asset($user->image)}}" alt="profile Pic" height="200" width="200">
                    </div>
                </div>
                <br>
                <br>
                <div class="row">
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label class="form-control-label">Exeutive Name: <span
                                    class="tx-danger">{{$user->user_name}}</span></label>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label class="form-control-label">Phone: <span
                                    class="tx-danger">{{$user->user_phone}}</span></label>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label class="form-control-label">Exeutive Email: <span
                                    class="tx-danger">{{$user->email}}</span></label>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label class="form-control-label">Joining Date: <span
                                    class="tx-danger">{{$user->joining_date}}</span></label>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label class="form-control-label">Address: <span
                                    class="tx-danger">{{$user->user_address}}</span></label>
                        </div>
                    </div>
                </div>

                <br>

            </div><!-- form-layout-footer -->
        </div><!-- form-layout -->

@endsection

@section('js')

@endsection

resources/views/pages/manage_executive/edit.blade.php
@extends('layouts.master')
@section('css')

    <script>
        function showMyImage(fileInput) {
            var files = fileInput.files;
            for (var i = 0; i < files.length; i++) {
                var file = files[i];
                var imageType = /image.*/;
                if (!file.type.match(imageType)) {
                    continue;
                }
                var img = document.getElementById("thumbnil");
                img.file = file;
                var reader = new FileReader();
                reader.onload = (function (aImg) {
                    return function (e) {
                        aImg.src = e.target.result;
                    };
                })(img);
                reader.readAsDataURL(file);
            }
        }
    </script>

@endsection

@section('content')
    <br>
    <div class="br-pagebody">
        <div class="br-section-wrapper">

            @include('include._message')

            <div class="row">
                <div class="col-lg-3">
                    <h5>Edit Executive Profile</h5>
                </div>
            </div>
            <hr>
            <br>

            <div class="form-layout form-layout-1">
                <form method="post" action="{{url('/executive/'.base64_encode($user->id))}}"
                      enctype="multipart/form-data">
                    @csrf
                    <div class="row">

                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="form-control-label">Executive Name<span class="tx-danger">*</span></label>
                                <input class="form-control" type="text" name="user_name"
                                       value="{{old('user_name') ?? $user->user_name}}" placeholder="executive name">
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="form-control-label">Executive Email<span
                                        class="tx-danger">*</span></label>
                                <input class="form-control" type="text" name="email"
                                       value="{{old('email') ?? $user->email }}" placeholder="executive email">
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="form-control-label">Executive Phone<span
                                        class="tx-danger">*</span></label>
                                <input class="form-control" type="text" name="user_phone"
                                       value="{{old('user_phone') ?? $user->user_phone}}" placeholder="executive phone">
                            </div>
                        </div>

                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="form-control-label">Joining Date:<span class="tx-danger">*</span></label>
                                <input type="text" id="datepicker" value="{{old('joining_date',$user->joining_date)}}" width="400" name="joining_date" class="form-control" placeholder="yy/mm/dd">
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="form-control-label">Password<span class="tx-danger">*</span></label>
                                <input class="form-control" type="password" name="password"
                                       value="{{old('password') ?? $user->password}}" placeholder="password">
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="form-control-label">Address<span class="tx-danger">*</span></label>
                                <input class="form-control" type="text" name="user_address"
                                       value="{{old('user_address') ?? $user->user_address}}" placeholder="address">
                            </div>
                        </div>
                    </div>

                    <div class="row">

                        <div class="col-lg-6">
                            <label class="form-control-label">Image<span class="tx-danger">*</span></label>
                            <input type="file" name="image" value="{{old('image') ?? $user->image}}" accept="image/*"
                                   onchange="showMyImage(this)"/>
                            <input type="hidden" value="{{old('image') ?? $user->image}}" name="oldimage"/>
                            <br/>
                            <img id="thumbnil" style="width:20%; margin-top:10px;" src="" alt="image"/>
                        </div>
                        <div class="col-lg-6">
                            <label class="form-control-label">Account Status<span class="tx-danger">*</span></label>
                            <select class="form-control select" name="status" data-placeholder="Choose Account Status">
                                @if ($user->status == "1")
                                    <option value="1">Active</option>
                                    <option value="0">Deactive</option>
                            </select>
                            @else
                                <option value="0">Deactive</option>
                                <option value="1">Active</option>
                                </select>
                            @endif

                        </div>
                    </div>
                    <br>

                    <div class="form-layout-footer">
                        <button class="btn btn-info">Update Information</button>

                    </div><!-- form-layout-footer -->
            </div><!-- form-layout -->

@endsection

@section('js')

<script>
        $("#datepicker").datepicker({ dateFormat: "yy-mm-dd" });
</script>

@endsection

resources/views/pages/manage_executive/index.blade.php
@extends('layouts.master')
@section('css')
<link href="{{asset('public/user/lib/@fortawesome/fontawesome-free/css/all.min.css')}}" rel="stylesheet">
<link href="{{asset('public/user/lib/ionicons/css/ionicons.min.css')}}" rel="stylesheet">
<link href="{{asset('public/user/lib/highlightjs/styles/github.css')}}" rel="stylesheet">
<link href="{{asset('public/user/lib/select2/css/select2.min.css')}}" rel="stylesheet">
<link href="{{asset('public/user/lib/datatables.net-dt/css/jquery.dataTables.min.css')}}" rel="stylesheet">
<link href="{{asset('public/user/lib/datatables.net-responsive-dt/css/responsive.dataTables.min.css')}}"
    rel="stylesheet">

@endsection
@section('content')
<br>

<div class="br-pagebody">
    <div class="br-section-wrapper">
        @include('include._message')
        <div class="row">
            <div class="col-lg-6">
                <h6 class="br-section-label">All Executive List</h6>
            </div>



            <div class="col-lg-2 offset-lg-4">
                <a href="{{route('executive.create')}}" class="btn btn-primary" style:"margin-left: 100px ">Add New Executive</a>
              </div>
          </div>

        </br>


          <div class=" table-wrapper">
                    <table id="datatable" class="table-responsive" style="width:100%">
                        <thead>
                            <tr>
                                <th class="wd-15p">Executive Name</th>
                                <th class="wd-20p">Executive Phone</th>
                                <th class="wd-20p">Executive Email</th>
                                <th class="wd-15p">Joining Date</th>
                                <th class="wd-15p">Account Status</th>
                                <th class="wd-10p">Action</th>
                            </tr>
                        </thead>

                    </table>
            </div><!-- table-wrapper -->

        </div>

        <div id="confirmModal" class="modal fade" role="dialog">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h2 class="modal-title">Confirmation</h2>
                    </div>
                    <div class="modal-body">
                        <h4 align="center" style="margin:0;">Are you sure you want to remove this data?</h4>
                    </div>
                    <div class="modal-footer">
                        <button type="button" name="ok_button" id="ok_button" class="btn btn-danger">OK</button>
                        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                    </div>
                </div>
            </div>
        </div>

    </div>

    @endsection

    @section('js')

    <script src="{{asset('public/user/lib/datatables.net/js/jquery.dataTables.min.js')}}"></script>
    <script src="{{asset('public/user/lib/datatables.net-dt/js/dataTables.dataTables.min.js')}}"></script>
    <script src="{{asset('public/user/lib/datatables.net-responsive/js/dataTables.responsive.min.js')}}"></script>
    <script src="{{asset('public/user/lib/datatables.net-responsive-dt/js/responsive.dataTables.min.js')}}"></script>
    <script src="{{asset('public/user/lib/select2/js/select2.min.js')}}"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.1/js/dataTables.buttons.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.1/js/buttons.print.min.js"></script>

    <script>
        $(document).ready(function(){

        $('#datatable').DataTable({
        processing: true,
        serverSide: true,
        responsive: true,
        autoWidth: true,
        scrollCollapse: true,
        jQueryUI: true,
        dom: 'Bfrtip',
        buttons: [
        'print'
        ],
        ajax: {
        url: "{{ route('executive.index') }}",
        },
        columns: [
        {
            data: 'user_name',
            name: 'user_name'
        },
        {
            data: 'user_phone',
            name: 'user_phone'
        },
        {
            data: 'email',
            name: 'email'
        },
        {
            data: 'joining_date',
            name: 'joining_date'
        },
        {
                    data: 'status',
                    name: 'status',
                    render: function(data){
                        return data == '1' ? '<span class="badge badge-pill badge-success">Active</span>' : '<span class="badge badge-pill badge-danger">Inactive</span>'
                    }
        },
        {
            data: 'action',
            name: 'action',
            orderable: false
        }
        ]
        });


 var user_id;

 $(document).on('click', '.delete', function(){
  user_id = $(this).attr('id');
  $('#confirmModal').modal('show');
 });

 $('#ok_button').click(function(){
  $.ajax({
    url:"{{route('medicine.destroy')}}",
    data: { user_id: user_id },
    beforeSend:function(){
    $('#ok_button').text('Deleting...');
   },
   success:function(data)
   {
    setTimeout(function(){
     $('#confirmModal').modal('hide');
     $('#datatable').DataTable().ajax.reload();

    });
   }
  })
 });

 });

    </script>

    @endsection