routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/login', 'LoginController@index')->name('login.index');
Route::post('/login', 'LoginController@authenticated');
Route::get('/logout', 'LoginController@SignOut')->name('logout.index');

//middleware for check login
Route::group(['middleware' => ['login']], function () {

    //Dashboard
    Route::get('/', 'HomeController@index')->name('home.index');

    //point of sale
    Route::get('pointofsale/', 'PointOfSaleController@index')->name('pointofsale.index');
    Route::post('pointofsale/searchlive', 'PointOfSaleController@liveSearchMedicine')->name('pointofsale.liveSearch');
    Route::post('pointofsale/search/medicine', 'PointOfSaleController@medicinSearch')->name('pointofsale.searchMedicine');

    //purchase Medicine
    Route::get('purchasemedicine/', 'PurchaseController@index')->name('purchase.index');
    Route::post('purchasemedicine/searchlive', 'PurchaseController@liveSearchMedicine')->name('purchase.liveSearch');
    Route::post('purchasemedicine/search/medicine','PurchaseController@medicinSearch')->name('purchase.searchMedicine');


    //invoice routes
     //invoice routes
    Route::post('/invoice', 'InvoiceController@addtocart')->name('invoice.add');
    Route::post('/invoice/save', 'InvoiceController@saveInvoice')->name('invoice.save');
    Route::get('/invoice/{id}', 'InvoiceController@deleteInvoiceItem')->name('invoice.delete');


    //Manage Category
    Route::get('/Category/', 'CategoryController@index')->name('Category.index');
    Route::get('/Category/create', 'CategoryController@create')->name('Category.create');
    Route::post('/Category', 'CategoryController@store')->name('Category.store');
    Route::get('/Category/edit/{id}', 'CategoryController@edit')->name('Category.edit');
    Route::patch('/Category/{id}', 'CategoryController@update')->name('Category.update');
    Route::get('/Category/destroy', 'CategoryController@destroy')->name('Category.destroy');

    //Manage Medicine
    Route::get('/medicine/list', 'MedicineController@index')->name('medicine.index');
    Route::get('/medicine/create', 'MedicineController@create')->name('medicine.create');
    Route::post('/medicine/store', 'MedicineController@store')->name('medicine.store');
    Route::get('/medicine/destroy', 'MedicineController@destroy')->name('medicine.destroy');
    Route::get('/medicine/edit/{id}', 'MedicineController@edit')->name('medicine.edit');
    Route::post('/medicine/{id}', 'MedicineController@update')->name('medicine.update');
    Route::get('/medicine/shortage', 'MedicineController@shortage')->name('medicine.shortage');
    Route::get('/medicine/details/{id}', 'MedicineController@details')->name('medicine.details');
    Route::get('/medicine/expired', 'MedicineController@expired')->name('medicine.expired');
    Route::get('/medicine/nearexpired', 'MedicineController@nearExpired')->name('medicine.nearexpired');

    //Manage Executives
    Route::resource('executive', 'ExecutiveController');
    Route::post('/executive/{id}', 'ExecutiveController@update')->name('executive.update');

    //Settings
    Route::get('/setting/activitylog', 'SettingController@activityLog')->name('setting.activity');
    Route::get('/setting/remainder', 'SettingController@remainderSetting')->name('setting.remainder');
    Route::post('/setting/remainder', 'SettingController@remainderChange')->name('setting.update');

    Route::get('/medicine/search', 'MedicineController@searchByGenericOrClassName')->name('medicine.search');

    //Manage Expenses catagory
    Route::get('/expense-category', 'ExpensecategoryController@index')->name('expense-category.index');
    Route::get('/expense-category/create', 'ExpensecategoryController@create')->name('expense-category.create');
    Route::post('/expense-category', 'ExpensecategoryController@store')->name('expense-category.store');
    Route::get('/expense-category/{id}', 'ExpensecategoryController@edit')->name('expense-category.edit');
    Route::patch('/expense-category/{id}', 'ExpensecategoryController@update')->name('expense-category.update');
    Route::get('/destory-expense-category', 'ExpensecategoryController@destroy')->name('expense-category.destroy');

    //expense related route
    Route::resource('expense', 'ExpenseController');

    //Manage Supplier
    Route::resource('supplier', 'SupplierController');
    Route::post('/supplier/{id}', 'SupplierController@update')->name('supplier.update');
    Route::get('/delete-supplier', 'SupplierController@delete')->name('supplier.delete');
    Route::get('/supplier/details', 'SupplierController@details')->name('supplier.details');



    //report related routes
     Route::get('/report/salesitems', 'SalesItemsController@index')->name('salesitem.index');
     Route::get('/report/date-wise-invoices-index', 'SalesItemsController@dateWiseInvoiceIndex')->name('datewise.index');
     Route::post('/report/date-wise-invoices-list', 'InvoiceController@dateWiseInvoiceReport')->name('datewise.Invoices');
     Route::get('/report/invoice-details/{invoice_number}', 'SalesItemsController@invoiceDetails')->name('invoice.details');
});

resources/views/pages/manage_expenses/expenses/create.blade.php
@extends('layouts.master')
@section('css')



@endsection

@section('content')
<br>
   
      
      <div class="br-pagebody">
        <div class="br-section-wrapper">
           @include('include._message')
          <div class="row">

            <div class="col-lg-3">
                <h5>New Expense Category</h5>
            </div> 
            <div class="col-lg-3 offset-lg-6">        
                <a href="{{route('expense-category.index')}}" class="btn btn-primary">All Expense Category List</a>
            </div>
        </div>
          <hr>
          <div class="row">
            <div cla></div>
          </div>

          <div class="form-layout form-layout-1">
            <form action="{{route('expense.store')}}" method="POST">
              @csrf
              <div class="row">
                <div class="col-lg-6">


                <div class="form-group">
                  <label class="form-control-label" for="title"> Title <span class="tx-danger">*</span></label>
                  <input class="form-control" id="title"  type="text" name="title" value="{{old('title')}}" placeholder="Enter Expense title">
                </div>
                
              </div>

                   
  
              <div class="col-lg-6">
                 <div class="form-group">
                    <label  class="form-control-label">Choose Category</label>
                         <select class="chosen-select form-control" name="expense_category_id" id="form-field-select-3" data-placeholder="Choose a status">
                          @foreach($expense_categories as $expensecategory)
                               <option value="{{$expensecategory->id}}">{{$expensecategory->expense_category_name}}</option>
                          @endforeach
                          </select>
                                      
                   </div>
                
              </div>
             </div> 


             <div class="row">

              <div class ="col-lg-6">
                 <div class="form-group">
                  <label class="form-control-label"  for="amount">Amount<span class="tx-danger">*</span></label>
                  <input class="form-control" type="number" id="amount" name="expense_amount" value="{{old('expense_amount')}}" placeholder="amount">
                </div>
              </div>

               <div class="col-lg-6">
                        <div class="form-group">
                            <label class="form-control-label">Date<span class="tx-danger">*</span></label>
                            <input type="text" id="datepicker" value="{{old('expense_date')}}" width="400"
                                name="expense_date" class="form-control" placeholder="yy/mm/dd">
                        </div>
              </div>


              

             </div>           

             <div class="form-group">
                      <label class="control-label"> Expense Category description <span class="tx-danger">*</span></label>
                      <div>
                          <textarea class="form-control" name="expense_description" cols="108" rows="5">
                              {{old('expense_description')}}
                          </textarea>
                                
                      </div>
             </div>


                

              <div class="form-layout-footer">
                <input type="submit" value="Save" class="btn btn-primary">
             
              </div><!-- form-layout-footer -->

             </form> 
            
                
           
           
            </div><!-- row -->

           
          </div><!-- form-layout -->
        </div>

@endsection

@section('js')
<script>
        $("#datepicker").datepicker({ dateFormat: "yy-mm-dd" });
    </script>


@endsection

resources/views/pages/manage_expenses/expenses/index.blade.php
@extends('layouts.master')
 @section('css')
    <link href="{{asset('public/user/lib/@fortawesome/fontawesome-free/css/all.min.css')}}" rel="stylesheet">
    <link href="{{asset('public/user/lib/ionicons/css/ionicons.min.css')}}" rel="stylesheet">
    <link href="{{asset('public/user/lib/highlightjs/styles/github.css')}}" rel="stylesheet">
    <link href="{{asset('public/user/lib/select2/css/select2.min.css')}}" rel="stylesheet">
    <link href="{{asset('public/user/lib/datatables.net-dt/css/jquery.dataTables.min.css')}}" rel="stylesheet">
    <link href="{{asset('public/user/lib/datatables.net-responsive-dt/css/responsive.dataTables.min.css')}}" rel="stylesheet">

 @endsection
 @section('content')
 <br>

      <div class="br-pagebody">
        <div class="br-section-wrapper">
            @include('include._message')
          <div class="row">
              <div class="col-lg-6">
                <h6 class="br-section-label">All Expense List</h6>
              </div>



              <div class="col-lg-2 offset-lg-4">
                  <a href="{{route('expense.create')}}" class="btn btn-primary" style:"margin-left: 100px ">Add New Expense</a>
              </div>
          </div>

        </br>


          <div class="table-wrapper">
            <table id="datatable" class="table display responsive nowrap">
              <thead>
                <tr>
                  <th class="wd-15p">Title</th>
                  <th class="wd-15p">Amount</th>
                  <th class="wd-15p">Date</th>
                  <th class="wd-10p">Action</th>
                </tr>
              </thead>

            </table>
          </div><!-- table-wrapper -->

      </div>

      <div id="confirmModal" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h2 class="modal-title">Confirmation</h2>
            </div>
            <div class="modal-body">
                <h4 align="center" style="margin:0;">Are you sure you want to remove this data?</h4>
            </div>
            <div class="modal-footer">
             <button type="button" name="ok_button" id="ok_button" class="btn btn-danger">OK</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
            </div>
        </div>
    </div>
  </div>

 </div>

    @endsection

    @section('js')


   <script src="{{asset('public/user/lib/datatables.net/js/jquery.dataTables.min.js')}}"></script>
    <script src="{{asset('public/user/lib/datatables.net-dt/js/dataTables.dataTables.min.js')}}"></script>
    <script src="{{asset('public/user/lib/datatables.net-responsive/js/dataTables.responsive.min.js')}}"></script>
    <script src="{{asset('public/user/lib/datatables.net-responsive-dt/js/responsive.dataTables.min.js')}}"></script>
    <script src="{{asset('public/user/lib/select2/js/select2.min.js')}}"></script>


    <script>

     $(document).ready(function(){
        $('#datatable').DataTable({
        paging: true,
        processing: true,
        serverSide: true,
        responsive: true,
        autoWidth: true,
        scrollCollapse: true,
        jQueryUI: true,
        ajax: {
        url: "{{ route('expense.index') }}",
        },
        columns: [
        {
            data: 'title',
            name: 'title'
        },

        {
            data: 'expense_amount',
            name: 'expense_amount'
        },
        {
            data: 'expense_date',
            name: 'expense_date'
        },

        {
            data: 'action',
            name: 'action',
            orderable: false
        }
        ]
        });


 });


</script>

 @endsection

resources/views/pages/manage_expenses/expenses/show.blade.php
@extends('layouts.master')
@section('css')
<style>
  hr {
    display: block;
    margin-top: 0.5em;
    margin-bottom: 0.5em;
    margin-left: auto;
    margin-right: auto;
    border-style: inset;
    border-width: 1px;
  }
</style>


@endsection

@section('content')
<br>
      <div class="br-pagebody">
        <div class="br-section-wrapper">


@include('include._message')



<br>
    <div class="br-pagebody">
        <div class="br-section-wrapper" style="background-color:powderblue">


            <div class="row">
                <div class="col-lg-3">
                    <h5 style="color: black">Executive Details</h5>
                </div>
            </div>
            <hr>
                <br>
                <br>
                <div class="row">
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label class="form-control-label">Expense Category :<span
                                    class="tx-danger">{{$expense->expensecategory->expense_category_name}}</span></label>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label class="form-control-label">Expense For: <span
                                    class="tx-danger">{{$expense->title}}</span></label>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label class="form-control-label">Expense Amount: <span
                                    class="tx-danger">{{$expense->expense_amount}}</span></label>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label class="form-control-label">Expense Date: <span
                                    class="tx-danger">{{$expense->expense_date}}</span></label>
                        </div>
                    </div>
                </div>


                <div class="row">
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label class="form-control-label">Address: <span
                                    class="tx-danger">{{$expense->expense_description}}</span></label>
                        </div>
                    </div>

                </div>

                <br>

            </div><!-- form-layout-footer -->
        </div><!-- form-layout -->


         
            
              
    
        

@endsection

@section('js')

@endsection