routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/login', 'LoginController@index')->name('login.index');
Route::post('/login', 'LoginController@authenticated');
Route::get('/logout', 'LoginController@SignOut')->name('logout.index');

//middleware for check login
Route::group(['middleware' => ['login']], function () {

    //Dashboard
    Route::get('/', 'HomeController@index')->name('home.index');

    //point of sale
    Route::get('pointofsale/', 'PointOfSaleController@index')->name('pointofsale.index');
    Route::post('pointofsale/searchlive', 'PointOfSaleController@liveSearchMedicine')->name('pointofsale.liveSearch');
    Route::post('pointofsale/search/medicine', 'PointOfSaleController@medicinSearch')->name('pointofsale.searchMedicine');

    //purchase Medicine
    Route::get('purchasemedicine/', 'PurchaseController@index')->name('purchase.index');
    Route::post('purchasemedicine/searchlive', 'PurchaseController@liveSearchMedicine')->name('purchase.liveSearch');
    Route::post('purchasemedicine/search/medicine','PurchaseController@medicinSearch')->name('purchase.searchMedicine');


    //invoice routes
     //invoice routes
    Route::post('/invoice', 'InvoiceController@addtocart')->name('invoice.add');
    Route::post('/invoice/save', 'InvoiceController@saveInvoice')->name('invoice.save');
    Route::get('/invoice/{id}', 'InvoiceController@deleteInvoiceItem')->name('invoice.delete');


    //Manage Category
    Route::get('/Category/', 'CategoryController@index')->name('Category.index');
    Route::get('/Category/create', 'CategoryController@create')->name('Category.create');
    Route::post('/Category', 'CategoryController@store')->name('Category.store');
    Route::get('/Category/edit/{id}', 'CategoryController@edit')->name('Category.edit');
    Route::patch('/Category/{id}', 'CategoryController@update')->name('Category.update');
    Route::get('/Category/destroy', 'CategoryController@destroy')->name('Category.destroy');

    //Manage Medicine
    Route::get('/medicine/list', 'MedicineController@index')->name('medicine.index');
    Route::get('/medicine/create', 'MedicineController@create')->name('medicine.create');
    Route::post('/medicine/store', 'MedicineController@store')->name('medicine.store');
    Route::get('/medicine/destroy', 'MedicineController@destroy')->name('medicine.destroy');
    Route::get('/medicine/edit/{id}', 'MedicineController@edit')->name('medicine.edit');
    Route::post('/medicine/{id}', 'MedicineController@update')->name('medicine.update');
    Route::get('/medicine/shortage', 'MedicineController@shortage')->name('medicine.shortage');
    Route::get('/medicine/details/{id}', 'MedicineController@details')->name('medicine.details');
    Route::get('/medicine/expired', 'MedicineController@expired')->name('medicine.expired');
    Route::get('/medicine/nearexpired', 'MedicineController@nearExpired')->name('medicine.nearexpired');

    //Manage Executives
    Route::resource('executive', 'ExecutiveController');
    Route::post('/executive/{id}', 'ExecutiveController@update')->name('executive.update');

    //Settings
    Route::get('/setting/activitylog', 'SettingController@activityLog')->name('setting.activity');
    Route::get('/setting/remainder', 'SettingController@remainderSetting')->name('setting.remainder');
    Route::post('/setting/remainder', 'SettingController@remainderChange')->name('setting.update');

    Route::get('/medicine/search', 'MedicineController@searchByGenericOrClassName')->name('medicine.search');

    //Manage Expenses catagory
    Route::get('/expense-category', 'ExpensecategoryController@index')->name('expense-category.index');
    Route::get('/expense-category/create', 'ExpensecategoryController@create')->name('expense-category.create');
    Route::post('/expense-category', 'ExpensecategoryController@store')->name('expense-category.store');
    Route::get('/expense-category/{id}', 'ExpensecategoryController@edit')->name('expense-category.edit');
    Route::patch('/expense-category/{id}', 'ExpensecategoryController@update')->name('expense-category.update');
    Route::get('/destory-expense-category', 'ExpensecategoryController@destroy')->name('expense-category.destroy');

    //expense related route
    Route::resource('expense', 'ExpenseController');

    //Manage Supplier
    Route::resource('supplier', 'SupplierController');
    Route::post('/supplier/{id}', 'SupplierController@update')->name('supplier.update');
    Route::get('/delete-supplier', 'SupplierController@delete')->name('supplier.delete');
    Route::get('/supplier/details', 'SupplierController@details')->name('supplier.details');



    //report related routes
     Route::get('/report/salesitems', 'SalesItemsController@index')->name('salesitem.index');
     Route::get('/report/date-wise-invoices-index', 'SalesItemsController@dateWiseInvoiceIndex')->name('datewise.index');
     Route::post('/report/date-wise-invoices-list', 'InvoiceController@dateWiseInvoiceReport')->name('datewise.Invoices');
     Route::get('/report/invoice-details/{invoice_number}', 'SalesItemsController@invoiceDetails')->name('invoice.details');
});

resources/views/pages/manage_supplier/create.blade.php
@extends('layouts.master')
@section('css')
    <style>
        hr {
            display: block;
            margin-top: 0.5em;
            margin-bottom: 0.5em;
            margin-left: auto;
            margin-right: auto;
            border-style: inset;
            border-width: 1px;
        }
    </style>


@endsection

@section('content')
    <br>
    <div class="br-pagebody">
        <div class="br-section-wrapper">

            @include('include._message')

            <div class="row">
                <div class="col-lg-3">
                    <h5>Add New Supplier</h5>
                </div>
            </div>
            <hr>
            <br>

            <div class="form-layout form-layout-1">
                <form method="POST" action="{{route('supplier.store')}}" >
                    @csrf

                    <div class="row">
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="form-control-label">Supplier Name<span class="tx-danger">*</span></label>
                                <input class="form-control" type="text" name="supplier_name" value="{{old('supplier_name')}}"
                                       placeholder="Full Name" required>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="form-control-label">Supplier Phone<span
                                        class="tx-danger">*</span></label>
                                <input class="form-control" type="text" name="supplier_phone" value="{{old('supplier_phone')}}"
                                       placeholder="Phone" required>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="form-control-label">Supplier Email<span
                                        class="tx-danger"></span></label>
                                <input class="form-control" type="email" name="supplier_email" value="{{old('supplier_email')}}"
                                       placeholder="Email">
                            </div>
                        </div>


                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="form-control-label">Supplier Address<span class="tx-danger">*</span></label>
                                <input class="form-control" type="text" name="supplier_address" value="{{old('supplier_address')}}"
                                       placeholder="Address" required>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="form-control-label">Supplier Type<span class="tx-danger"></span>*</label>
                                <input class="form-control" type="text" name="supplier_type" value="{{old('supplier_type')}}"
                                       placeholder="Type" required>
                            </div>
                        </div>

                     <div class="col-lg-6">
                        <div class="form-group">
                            <label class="control-label">Description<span class="tx-danger"></span></label>
                            <div>
                                <textarea name="description" class="form-control">
                            {{old('description')}}
                          </textarea>
                            </div>
                        </div>
                    </div>
                </div>

                    <br>
                    <div class="form-layout-footer">
                        <button class="btn btn-info">Save Information</button>
                    </div><!-- form-layout-footer -->
            </div><!-- form-layout -->

@endsection

@section('js')

@endsection

resources/views/pages/manage_supplier/edit.blade.php
@extends('layouts.master')
@section('css')
    <style>
        hr {
            display: block;
            margin-top: 0.5em;
            margin-bottom: 0.5em;
            margin-left: auto;
            margin-right: auto;
            border-style: inset;
            border-width: 1px;
        }
    </style>


@endsection

@section('content')
    <br>
    <div class="br-pagebody">
        <div class="br-section-wrapper">

            @include('include._message')

            <div class="row">
                <div class="col-lg-3">
                    <h5>Edit Supplier Information</h5>
                </div>
            </div>
            <hr>
            <br>

            <div class="form-layout form-layout-1">
                <form method="POST" action="{{route('supplier.update',$supplier->id)}}" >
                    @csrf

                    <div class="row">
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="form-control-label">Supplier Name<span class="tx-danger">*</span></label>
                                <input class="form-control" type="text" name="supplier_name" value="{{old('supplier_name',$supplier->supplier_name)}}"
                                        required>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="form-control-label">Supplier Phone<span
                                        class="tx-danger">*</span></label>
                                <input class="form-control" type="text" name="supplier_phone" value="{{old('supplier_phone',$supplier->supplier_phone)}}"
                                       placeholder="Phone" required>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="form-control-label">Supplier Email<span
                                        class="tx-danger"></span></label>
                                <input class="form-control" type="email" name="supplier_email" value="{{old('supplier_email',$supplier->supplier_email)}}"
                                       placeholder="Email">
                            </div>
                        </div>


                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="form-control-label">Supplier Address<span class="tx-danger">*</span></label>
                                <input class="form-control" type="text" name="supplier_address" value="{{old('supplier_address',$supplier->supplier_address)}}"
                                       placeholder="Address" required>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="form-control-label">Supplier Type<span class="tx-danger"></span>*</label>
                                <input class="form-control" type="text" name="supplier_type" value="{{old('supplier_type',$supplier->supplier_type)}}"
                                       placeholder="Type" required>
                            </div>
                        </div>

                     <div class="col-lg-6">
                        <div class="form-group">
                            <label class="control-label">Description<span class="tx-danger"></span></label>
                            <div>
                                <textarea name="description" class="form-control">
                            {{old('description',$supplier->description)}}
                          </textarea>
                            </div>
                        </div>
                    </div>
                </div>

                    <br>
                    <div class="form-layout-footer">
                        <button class="btn btn-info">Update Information</button>
                    </div><!-- form-layout-footer -->
            </div><!-- form-layout -->

@endsection

@section('js')

@endsection

resources/views/pages/manage_supplier/index.blade.php
@extends('layouts.master')
@section('css')
<link href="{{asset('public/user/lib/@fortawesome/fontawesome-free/css/all.min.css')}}" rel="stylesheet">
<link href="{{asset('public/user/lib/ionicons/css/ionicons.min.css')}}" rel="stylesheet">
<link href="{{asset('public/user/lib/highlightjs/styles/github.css')}}" rel="stylesheet">
<link href="{{asset('public/user/lib/select2/css/select2.min.css')}}" rel="stylesheet">
<link href="{{asset('public/user/lib/datatables.net-dt/css/jquery.dataTables.min.css')}}" rel="stylesheet">
<link href="{{asset('public/user/lib/datatables.net-responsive-dt/css/responsive.dataTables.min.css')}}"
    rel="stylesheet">

@endsection
@section('content')
<br>

<div class="br-pagebody">
    <div class="br-section-wrapper">
        @include('include._message')
        <div class="row">
            <div class="col-lg-6">
                <h6 class="br-section-label">All Supplier List</h6>
            </div>



            <div class="col-lg-2 offset-lg-4">
                <a href="{{route('supplier.create')}}" class="btn btn-primary" style:"margin-left: 100px ">Add New Supplier</a>
              </div>
          </div>

        </br>


          <div class=" table-wrapper">
                    <table id="datatable" class="table-responsive" style="width:100%">
                        <thead>
                            <tr>
                                <th class="wd-5p">Name</th>
                                <th class="wd-5p">Phone</th>
                                <th class="wd-5p">Email</th>
                                <th class="wd-5p">Type</th>
                                <th class="wd-5p">Action</th>
                            </tr>
                        </thead>

                    </table>
            </div><!-- table-wrapper -->

        </div>

        <div id="confirmModal" class="modal fade" role="dialog">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h2 class="modal-title">Confirmation</h2>
                    </div>
                    <div class="modal-body">
                        <h4 align="center" style="margin:0;">Are you sure you want to remove this data?</h4>
                    </div>
                    <div class="modal-footer">
                        <button type="button" name="ok_button" id="ok_button" class="btn btn-danger">OK</button>
                        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                    </div>
                </div>
            </div>
        </div>

        <div id="DetailsModal" class="modal fade" role="dialog">
            <div class="modal-dialog">
                <div class="modal-content">
                    <table id="moduleTable" class="table table-bordered table-colored table-dark">
                        <tbody>
                            <tr>
                                <td colspan="2" style="text-align:center"><strong>Supplier Details</strong></td>
                            </tr>
                            <tr>
                                <th class="wd-10p">Name</th>
                                <td id="supplier_name"></td>
                            </tr>
                            <tr>
                                <th class="wd-35p">Phone</th>
                                <td id="supplier_phone"></td>
                            </tr>
                            <tr>
                                <th class="wd-20p">Email</th>
                                <td id="supplier_email"></td>
                            </tr>
                            <tr>
                                <th class="wd-20p">Address</th>
                                <td id="supplier_address"></td>
                            </tr>

                            <tr>
                                <th class="wd-20p">Type</th>
                                <td id="supplier_type"></td>
                            </tr>
                            <tr>
                                <th class="wd-20p">Description</th>
                                <td id="description"></td>
                            </tr>
                            <tr>
                                <th class="wd-20p">Adding Date</th>
                                <td id="adding_date"><span id="aa"></span></td>

                            </tr>
                        </tbody>
                    </table>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Done</button>
                    </div>
                </div>
            </div>
        </div>


    </div>

    @endsection

    @section('js')

    <script src="{{asset('public/user/lib/datatables.net/js/jquery.dataTables.min.js')}}"></script>
    <script src="{{asset('public/user/lib/datatables.net-dt/js/dataTables.dataTables.min.js')}}"></script>
    <script src="{{asset('public/user/lib/datatables.net-responsive/js/dataTables.responsive.min.js')}}"></script>
    <script src="{{asset('public/user/lib/datatables.net-responsive-dt/js/responsive.dataTables.min.js')}}"></script>
    <script src="{{asset('public/user/lib/select2/js/select2.min.js')}}"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.1/js/dataTables.buttons.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.1/js/buttons.print.min.js"></script>

    <script>
        $(document).ready(function(){

        $('#datatable').DataTable({
        paging: true,
        processing: true,
        serverSide: true,
        responsive: true,
        autoWidth: true,
        scrollCollapse: true,
        jQueryUI: true,
        dom: 'Bfrtip',
        buttons: [
        'print'
        ],
        ajax: {
        url: "{{ route('supplier.index') }}",
        },
        columns: [
        {
            data: 'supplier_name',
            name: 'supplier_name'
        },
        {
            data: 'supplier_phone',
            name: 'supplier_phone'
        },
        {
            data: 'supplier_email',
            name: 'supplier_email'
        },
        {
            data: 'supplier_type',
            name: 'supplier_type'
        },
        {
            data: 'action',
            name: 'action',
            orderable: false
        }
        ]
        });


 var supplier_id;

 $(document).on('click', '.delete', function(){
  supplier_id = $(this).attr('id');
  $('#confirmModal').modal('show');
 });

 $('#ok_button').click(function(){
  $.ajax({
    url:"{{route('supplier.delete')}}",
    data: {supplier_id: supplier_id},
    beforeSend:function(){
    $('#ok_button').text('Deleting...');
   },
   success:function(data)
   {
    setTimeout(function(){
     $('#confirmModal').modal('hide');
     $('#datatable').DataTable().ajax.reload();
    });
   }
  })
 });



 $(document).on('click', '.details', function(){
  var uid = $(this).attr('id');
  $.ajax({
   url:"supplier/"+uid,
   dataType:"json",
   success:function(data)
   {
    $('#supplier_name').text(data.result.supplier_name);
    $('#supplier_phone').text(data.result.supplier_phone);
    $('#supplier_email').text(data.result.supplier_email);
    $('#supplier_address').text(data.result.supplier_address);
    $('#supplier_type').text(data.result.supplier_type);
    $('#description').text(data.result.description);
    $('#adding_date').text(data.result.adding_date);
    $('#DetailsModal').modal('show');
   }
  })

 });




 });

    </script>

    @endsection